### ISSUE TITLE
Recenser les ark des ms de la BnF référencés

### ISSUE THREAD

**Issue by architexte** [chartes/miroir#1]
# Classiques latins

| cote Paris Bibl. nat. de Fr. | classiques latins occs | url Gallica | att.source |
|------------------------------|------------------------|-------------|---------------------|
| fr. 881 | 4 | http://gallica.bnf.fr/ark:/12148/btv1b8449041w | fait |
| fr. 821 | 4 | http://gallica.bnf.fr/ark:/12148/btv1b9007157m | fait |
| fr. 282 | 4 | http://gallica.bnf.fr/ark:/12148/btv1b8451116z | fait |
| nouv. acq. fr. 1982 | 3 | http://gallica.bnf.fr/ark:/12148/btv1b52504365k | fait |
| fr. 728 | 3 | https://gallica.bnf.fr/ark:/12148/btv1b90599811 | fait |
| fr. 576 | 3 | http://gallica.bnf.fr/ark:/12148/btv1b9006864v | fait |
| fr. 38 | 3 | https://gallica.bnf.fr/ark:/12148/btv1b9059443m https://gallica.bnf.fr/ark:/12148/btv1b90594441 | fait |
| fr. 280 | 3 | https://gallica.bnf.fr/ark:/12148/btv1b9059946k | fait |
| fr. 25418 | 3 | https://gallica.bnf.fr/ark:/12148/btv1b9063364v | fait |
| fr. 24257 | 3 | non trouvé |  |
| fr. 2118 | 3 | https://gallica.bnf.fr/ark:/12148/btv1b9057403g | fait |
| fr. 1641 | 3 | https://gallica.bnf.fr/ark:/12148/btv1b90596632 | fait |
| fr. 1543 | 3 | http://gallica.bnf.fr/ark:/12148/btv1b90096858 | fait |
| fr. 12459 | 3 | http://gallica.bnf.fr/ark:/12148/btv1b9060931m | fait |
| fr. 1234 | 3 | non trouvé |  |
| nouv. acq. fr. 4804 | 2 | non trouvé |  |
| nouv. acq. fr. 4690 | 2 | non trouvé |  |
| nouv. acq. fr. 4531 | 2 | non trouvé |  |
| nouv. acq. fr. 1120 | 2 | non trouvé |  |
| lat. 14095 | 2 | https://gallica.bnf.fr/ark:/12148/btv1b10034660q | fait |
| fr. 926 | 2 | http://gallica.bnf.fr/ark:/12148/btv1b9059107q | fait |
| fr. 874 | 2 | http://gallica.bnf.fr/ark:/12148/btv1b90595807 | fait |
| fr. 287 | 2 | http://gallica.bnf.fr/ark:/12148/btv1b9009561h | fait |
| fr. 264-266 | 2 | https://gallica.bnf.fr/ark:/12148/btv1b90588584 https://gallica.bnf.fr/ark:/12148/btv1b9058859j https://gallica.bnf.fr/ark:/12148/btv1b9058857q | fait |
| fr. 263 | 2 | http://archivesetmanuscrits.bnf.fr/ark:/12148/cc78552b [https://gallica.bnf.fr/ark:/12148/btv1b8451118s] | fait |
| fr. 24307 | 2 | http://gallica.bnf.fr/ark:/12148/btv1b9063730f | fait |
| fr. 2327 | 2 | non trouvé |  |
| fr. 22547 | 2 | http://gallica.bnf.fr/ark:/12148/btv1b8449039t http://gallica.bnf.fr/ark:/12148/btv1b9063149g | fait |
| fr. 2125 | 2 | https://gallica.bnf.fr/ark:/12148/btv1b100212619 | fait |
| fr. 19138 | 2 | non trouvé |  |
| fr. 1604 | 2 | http://gallica.bnf.fr/ark:/12148/btv1b9058841v | fait |
| fr. 1593 | 2 | http://gallica.bnf.fr/ark:/12148/btv1b6000803p | fait |
| fr. 1563 | 2 | http://gallica.bnf.fr/ark:/12148/btv1b6000321w | fait |
| fr. 1235 | 2 | non trouvé |  |
| fr. 1233 | 2 | http://gallica.bnf.fr/ark:/12148/btv1b90591017 | fait |
| fr. 12239 | 2 | https://gallica.bnf.fr/ark:/12148/btv1b90616663 | fait |
| fr. 12238 | 2 | https://gallica.bnf.fr/ark:/12148/btv1b9061667h | fait |
| fr. 1097 | 2 | http://gallica.bnf.fr/ark:/12148/btv1b8529503m http://gallica.bnf.fr/ark:/12148/btv1b9007012p | fait |
| fr. 1096 | 2 | http://gallica.bnf.fr/ark:/12148/btv1b9058829d | fait |
| fr 12478 | 2 | http://gallica.bnf.fr/ark:/12148/btv1b10720679d | fait |
| Paris bibl. de l’Institut de France 264 | 1 | non trouvé |  |
| nouv. acq. lat. 2381 | 1 | non trouvé |  |
| nouv. acq. fr. 6535 | 1 | non trouvé |  |
| nouv. acq. fr. 6367 | 1 | non trouvé |  |
| nouv. acq. fr. 5094 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b6000371s | fait |
| nouv. acq. fr. 27401 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b10532600x | fait |
| nouv. acq. fr. 21471 | 1 | non trouvé |  |
| nouv. acq. fr. 20233 (ancien Phillipps 4355) | 1 | non trouvé |  |
| nouv. acq. fr. 20001 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b60003741 | fait |
| nouv. acq. fr. 15987 | 1 | non trouvé |  |
| nouv. acq. fr. 11675 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b105372523 | fait |
| nouv. acq. fr. 11198, f. 42 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b8449036k | fait |
| lat. 6643 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9076990m | fait |
| lat. 18424 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9078059b | fait |
| fr. 9749 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b8455786x | fait |
| fr. 9738 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9063084k | fait |
| fr. 9186 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b10722043w | fait |
| fr. 876-877 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9059080h http://gallica.bnf.fr/ark:/12148/btv1b9059579k | fait |
| fr. 875 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b8427253m | fait |
| fr. 873 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9059586q http://gallica.bnf.fr/ark:/12148/btv1b105224716 | fait |
| fr. 822 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b90592250 | fait |
| fr. 813 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9059152j | fait |
| fr. 812 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b6000313b http://gallica.bnf.fr/ark:/12148/btv1b84489653 | fait |
| fr. 809 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b52505477m http://gallica.bnf.fr/ark:/12148/btv1b10525468z | fait |
| fr. 738 | 1 | non trouvé |  |
| fr. 737 | 1 | non trouvé |  |
| fr. 727 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b531387393 | fait |
| fr. 720-721 | 1 | non trouvés |  |
| fr. 716-719 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b90581208 http://gallica.bnf.fr/ark:/12148/btv1b9007595p http://gallica.bnf.fr/ark:/12148/btv1b90581186 http://gallica.bnf.fr/ark:/12148/btv1b9058119m | fait |
| fr. 708-711 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b10525302d http://gallica.bnf.fr/ark:/12148/btv1b90581223 http://gallica.bnf.fr/ark:/12148/btv1b10525303v http://gallica.bnf.fr/ark:/12148/btv1b10525305r | fait |
| fr. 681-683 | 1 | non trouvé |  |
| fr. 6445 | 1 | non trouvé |  |
| fr. 6441 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b90075481 | fait |
| fr. 6440 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b90604270 | fait |
| fr. 6185 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9006774w | fait |
| fr. 578 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b105090864 http://gallica.bnf.fr/ark:/12148/btv1b9059382c | fait |
| fr. 577 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9059980m | fait |
| fr. 575 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b90589075 | fait |
| fr. 55-57 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9059131c http://gallica.bnf.fr/ark:/12148/btv1b9059132s http://gallica.bnf.fr/ark:/12148/btv1b90591299 | fait |
| fr. 54 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9007598x | fait |
| fr. 53 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9007599b | fait |
| fr. 47-49 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9009635c http://gallica.bnf.fr/ark:/12148/btv1b9009636s http://gallica.bnf.fr/ark:/12148/btv1b9009634z | fait |
| fr. 45-46 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9009640p http://gallica.bnf.fr/ark:/12148/btv1b90096413 http://gallica.bnf.fr/ark:/12148/btv1b90096391 | fait |
| fr. 44 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b90096480 http://gallica.bnf.fr/ark:/12148/btv1b9009649d | fait |
| fr. 42-43 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9009626d http://gallica.bnf.fr/ark:/12148/btv1b9009627t | fait |
| fr. 41 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9058204h | fait |
| fr. 36-37 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b52510225g https://gallica.bnf.fr/ark:/12148/btv1b52510138v | fait |
| fr. 35 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9058225p | fait |
| fr. 34 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b90589572 | fait |
| fr. 33 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9058961z | fait |
| fr. 31-32 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9009504g http://gallica.bnf.fr/ark:/12148/btv1b9009481x http://gallica.bnf.fr/ark:/12148/btv1b9009455f | fait |
| fr. 302 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9058254d https://gallica.bnf.fr/ark:/12148/btv1b9058255t | fait |
| fr. 301 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9007616d | fait |
| fr. 30 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9059010v | fait |
| fr. 296-299 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b10507210m http://gallica.bnf.fr/ark:/12148/btv1b9059950g http://gallica.bnf.fr/ark:/12148/btv1b105072112 http://gallica.bnf.fr/ark:/12148/btv1b9059951w http://gallica.bnf.fr/ark:/12148/btv1b9059948d http://gallica.bnf.fr/ark:/12148/btv1b105090669 http://gallica.bnf.fr/ark:/12148/btv1b9059949t | fait |
| fr. 292 | 1 | non trouvé |  |
| fr. 291 | 1 | non trouvé |  |
| fr. 290 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b53142051x | fait |
| fr. 288-289 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b90095492 http://gallica.bnf.fr/ark:/12148/btv1b90095603 | fait |
| fr. 286 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9009562x | fait |
| fr. 283-285 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b90095477 http://gallica.bnf.fr/ark:/12148/btv1b9009548n http://gallica.bnf.fr/ark:/12148/btv1b9009543k | fait |
| fr. 277-278 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9009569t http://gallica.bnf.fr/ark:/12148/btv1b9009570g | fait |
| fr. 276 | 1 | non trouvé |  |
| fr. 275 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9009695n | fait |
| fr. 273-274 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9058115z http://gallica.bnf.fr/ark:/12148/btv1b90070207 http://gallica.bnf.fr/ark:/12148/btv1b9009587r http://gallica.bnf.fr/ark:/12148/btv1b90095885 | fait |
| fr. 269-272 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9059163b http://gallica.bnf.fr/ark:/12148/btv1b9009599z http://gallica.bnf.fr/ark:/12148/btv1b9009589k http://gallica.bnf.fr/ark:/12148/btv1b9009598j | fait |
| fr. 268 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b90096784 | fait |
| fr. 267 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9058116c | fait |
| fr. 260-262 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9058188v http://gallica.bnf.fr/ark:/12148/btv1b9009690k http://gallica.bnf.fr/ark:/12148/btv1b90096910 | fait |
| fr. 259 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9058190x | fait |
| fr. 258 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9009692d http://gallica.bnf.fr/ark:/12148/btv1b9009693t | fait |
| fr. 257 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b10511088k | fait |
| fr. 25545 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9063357q | fait |
| fr. 25417 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b90636281 | fait |
| fr. 25416 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9063629f | fait |
| fr. 254 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b105452357 | fait |
| fr. 25397 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9063693m | fait |
| fr. 24396 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9063729s | fait |
| fr. 24309 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b100327663 | fait |
| fr. 24308 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b90637343 | fait |
| fr. 24231 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b90630798 | fait |
| fr. 24230 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9063613k | fait |
| fr. 23090-91 | 1 | non trouvé |  |
| fr. 22554 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9063494b | fait |
| fr. 2063 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9059919p | fait |
| fr. 20320 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b90619271 | fait |
| fr. 20319 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9061903m | fait |
| fr. 20318 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9061928f | fait |
| fr. 20316 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9063835v | fait |
| fr. 20315 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b525002846 | fait |
| fr. 20313-20314 | 1 | non trouvés |  |
| fr. 20312 ter | 1 | non trouvé |  |
| fr. 20311 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b525081639 | fait |
| fr. 20071-20072 | 1 | non trouvé https://gallica.bnf.fr/ark:/12148/btv1b10724340c | fait |
| fr. 20018 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b90633302 | fait |
| fr. 1949 | 1 | non trouvé |  |
| fr. 1948 | 1 | non trouvé |  |
| fr. 1947 | 1 | non trouvé |  |
| fr. 1946 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9059012p | fait |
| fr. 19152 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9062193k | fait |
| fr. 19137 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b6000353v | fait |
| fr. 19104 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9061960n | fait |
| fr. 1728 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b84473026 | fait |
| fr. 17272 | 1 | non trouvé |  |
| fr. 17080 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9061277h | fait |
| fr. 1652 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b90588517 | fait |
| fr. 1651 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9058837z | fait |
| fr. 15471 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9007348b | fait |
| fr. 15470 | 1 | non trouvé |  |
| fr. 15469 | 1 | non trouvé |  |
| fr. 15455 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9061358h | fait |
| fr. 1542 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9059210j | fait |
| fr. 1541 | 1 | non trouvé |  |
| fr. 1540 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9059892g | fait |
| fr. 1392 | 1 | non trouvé |  |
| fr. 12787 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9061778n | fait |
| fr. 12478 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b10720679d | fait |
| fr. 12360 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9060918r | fait |
| fr. 1232 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9059830c | fait |
| fr. 1231 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9060104z | fait |
| fr. 1230 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9059829q | fait |
| fr. 1229 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b8451600t | fait |
| fr. 12240 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9061665p | fait |
| fr. 12237 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9061668x | fait |
| fr. 1102 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9059092q | fait |
| fr. 1100-1101 | 1 | non trouvé https://gallica.bnf.fr/ark:/12148/btv1b9009532s | fait |
| fr. 1099 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b10537354c | fait |
| fr. 1098 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b10537240s http://gallica.bnf.fr/ark:/12148/btv1b90580717 | fait |
| fr. 1095 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9058832w | fait |
| fr. 1094 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9058820p | fait |
| fr. 1093 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b9058881c | fait |
| fr. 1092 | 1 | http://gallica.bnf.fr/ark:/12148/btv1b10537239d | fait |
| Rés. 4° Lb28. 15α | 1 | non trouvé |  |
| Rothschild IV.2.67 (2753) | 1 | non trouvé |  |

## Manuscrits juridiques
| cote Paris Bibl. nat. de Fr. | ms juridiques occs | url Gallica | att.source |
|------------------------------|--------------------|-------------|--------------|
| fr. 498 | 3 | http://gallica.bnf.fr/ark:/12148/btv1b8447185s | fait |
| fr. 22970 | 3 | https://gallica.bnf.fr/ark:/12148/btv1b8447870r | fait |
| nouv. acq. fr. 10046 | 2 | non trouvé |  |
| fr. 497 | 2 | http://gallica.bnf.fr/ark:/12148/btv1b9059383s | fait |
| fr. 496 | 2 | http://gallica.bnf.fr/ark:/12148/btv1b90593846 | fait |
| fr. 495 | 2 | http://gallica.bnf.fr/ark:/12148/btv1b84471866 | fait |
| fr. 25546 | 2 | http://gallica.bnf.fr/ark:/12148/btv1b90075162 | fait |
| fr. 20121 | 2 | https://gallica.bnf.fr/ark:/12148/btv1b9062037m | fait |
| fr. 20120 | 2 | https://gallica.bnf.fr/ark:/12148/btv1b8455783p | fait |
| fr. 20119 | 2 | https://gallica.bnf.fr/ark:/12148/btv1b90620381 | fait |
| fr. 20118 | 2 | https://gallica.bnf.fr/ark:/12148/btv1b84557828 | fait |
| fr. 200 | 2 | http://gallica.bnf.fr/ark:/12148/btv1b10720758h | fait |
| fr. 198 | 2 | http://gallica.bnf.fr/ark:/12148/btv1b90095388 | fait |
| fr. 1934 | 2 | non trouvé |  |
| fr. 1933 | 2 | https://gallica.bnf.fr/ark:/12148/btv1b10720750x | fait |
| fr. 1928 | 2 | https://gallica.bnf.fr/ark:/12148/btv1b90596899 | fait |
| fr. 1075 | 2 | https://gallica.bnf.fr/ark:/12148/btv1b90596936 | fait |
| fr. 1074 | 2 | https://gallica.bnf.fr/ark:/12148/btv1b9059667q | fait |
| fr. 1073 | 2 | https://gallica.bnf.fr/ark:/12148/btv1b90596684 | fait |
| fr. 1070 | 2 | http://gallica.bnf.fr/ark:/12148/btv1b107207214 | fait |
| fr. 1069 | 2 | https://gallica.bnf.fr/ark:/12148/btv1b90070133 | fait |
| fr. 1065 | 2 | non trouvé | - |
| fr. 1064 | 2 | https://gallica.bnf.fr/ark:/12148/btv1b8452541q | fait |
| fr. 1063 | 2 | https://gallica.bnf.fr/ark:/12148/btv1b9059651v?rk=42918;4 | fait |
| nouv. acq. fr. 4504 | 1 | non trouvé |  |
| nouv. acq. fr. 4138 | 1 | non trouvé |  |
| fr. 5245 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b10724336n | fait |
| fr. 2844 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9059006z | fait |
| fr. 2426 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b9059989b | fait |
| fr. 22969 | 1 | https://gallica.bnf.fr/ark:/12148/btv1b84478693 | fait |
| fr. 197 | 1 | non trouvé |  |
| fr. 1932 | 1 | non trouvé |  |
| Rés. F. 35 | 1 | non trouvé |  |

**Comment by TNAHMP** [comment]
@architexte - tableau rempli.

**Comment by TNAHMP** [comment]
Tous les manuscrits ont été ajoutés sur les éléments `<msDesc>` dans des `@source`, je ferme donc l'issue.
