### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by architexte** [chartes/miroir#8]
* normaliser les atts: `anchored`, `place`, `resp`, `target`, `type`, `xml:id`
* typer rigoureusement et normaliser
* notes dans les notes…

**Comment by TNAHMP** [comment]
[En cours.]

Premières remarques sur les différents encodages de note constatés :

+ **@type** toujours utilisé avec la valeur "msItem" *et* quand la note est à l'intérieur d'un <msItem> ; sauf deux valeurs "note" (inutiles ?) dans une structure div>l>note>app

**Comment by TNAHMP** [comment]
Après constatation que les deux //note/@type="note" correspondaient aux conditions des //note/@place="bottom", normalisation des deux //note concernées.

cf commit 9a9023d

**Comment by architexte** [comment]
**Bilan**

786 `note`:
* `@place="inline"` –  117/786 : les notes qu’on ne souhaite pas déporter en bas de page (par défaut `@place="bottom")`.
* `@resp` – 7/786 : identifie les rares (7) notes rédigées par les collaborateurs (`GP` et `HB`). Faut-il conserver cette information ? Pourquoi ?
* `@type="msItem"` – 40/786 : permet d’isoler les notes présentes dans l’élément `msItem`. Est-ce utile de conserver cet attribut qui n’est pas systématiquement renseigné ? Pourquoi ?

Dernière question : faut-il envisager de typer les notes, par ex. selon leur contenu (`app`…) ?

**Comment by TNAHMP** [comment]
**Réponses** (de FD) :

Les @resp et @type="msItem" peuvent être totalement éliminés des fichiers.

**Comment by TNAHMP** [comment]
**Bilan et dernière réponse :**

Les @resp et @type ont été éliminés (cf commits 73eaf2a et 04a89ac).
Il n'est pas utile de typer les notes en fonction de leur contenu.

Nous avons deux types de notes :
+ //note[not(@*)] - note générique placée par défaut en bas de page ;
+ //note[@place="inline"] - note gardée dans le corps du texte.
