### ISSUE TITLE
Identification des passages

### ISSUE THREAD

**Issue by architexte** [chartes/miroir#9]
Dans les éditions (`div[@type="edition"]`), les références des passages sont inscrites dans des `label`.  
TODO: normaliser et inscrire ces références en valeur d’att du bloc (`p`, `item`) ou du segment *inline* correspondant  (`seg`), par ex.
```xml
 <p xml:id="C.2.7.0"><label>[2.7.0]</label>…</p>
```

**Comment by architexte** [comment]
Done dans `authenticum.xml` pour les identifiants conformes au motif `C.[0-9]{2}.[0-9]{2}`.
Quelle doit être la granularité de cette identification des paragraphes (faut-il renseigner des @xml:id pour les motif de type `[0-9]{2}.[0-9]`, par exemple: `<p><label>[65.3]</label>`) ?
TODO: trancher avec FD.

**Comment by TNAHMP** [comment]
Travail en cours sur le codex_justinianus.xml.

Les passages sont édités plusieurs fois, à partir de manuscrits différents. Cela donne plusieurs passages "C.2.58", par exemple. **Il faut donc différencier les manifestations d'un même passage.** Je pense ajouter l'identifiant du manuscrit avant celui du passage.

Par exemple : `xml:id="orleans_392.C.2.58"` pour le passage C.2.58 dans le manuscrit Orléans 392.

("orleans_392" étant l'identifiant donné au `<msDesc>` du manuscrit.)

**Comment by TNAHMP** [comment]
@architexte : Principe appliqué aux autres fichiers sur la branche "xmlid", identifiants donnés à tous les fichiers xml du corpus juridique quand c'était nécessaire.
